version: '3.7'

services:
    bitemap:
        build:
            context:  ./services/web
            dockerfile: Dockerfile.prod
        command: gunicorn --bind 0.0.0.0:5001 manage:app
        volumes:
            - static_volume:/home/app/web/project/static
        env_file:
            - ./.env.prod
            # - db
        restart: unless-stopped
    # db:
    #     image: postgres:12-alpine
    #     volumes:
    #         - postgres_data:/var/lib/postgresql/data/
    #     env_file:
    #         - ./.env.prod.db
    #     restart: unless-stopped
    bitemap_nginx:
        build: ./services/nginx
        volumes:
            - static_volume:/home/app/web/project/static
        ports:
            - 5000:80
        depends_on:
            - web
        restart: unless-stopped

volumes:
    # postgres_data:
    static_volume:
